_welcome:
    pattern:  /
    defaults: { _controller: AoceuSiteBundle:Page:home }

# Pages
   
AoceuSiteBundlePageAbout:
    pattern:  /about
    defaults: { _controller: AoceuSiteBundle:Page:about }
    
AoceuSiteBundlePageContact:
    pattern:  /contact
    defaults: { _controller: AoceuSiteBundle:Page:contact }
    
# Blog
    
AoceuSiteBundleBlog:
    pattern:  /blog
    defaults: { _controller: AoceuSiteBundle:Blog:main }
